### ISSUE TITLE
OSoC App logo needed

### ISSUE THREAD

**Issue by saarinii** [upes-open/OSoC-DoorDarshan#9]
Need a logo for the app. The logo needs to match the colors of the app which is periwinkle. A mixture of Devanagari (Hindi language script) and English words. It needs to be like "दूरDarshan".

**Comment by yashh1711** [comment]
I've designed a logo. Need someone to review it

**Comment by yashh1711** [comment]
[DoorDarshan Logo](https://www.canva.com/design/DAFobZMCa9o/aeOpAPG2AOmwP8gnl_pfZQ/view?utm_content=DAFobZMCa9o&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)

Check and review please

**Comment by saarinii** [comment]
It's nice and could you send me this but just the illustration inside the circle??

**Comment by ArshdeepKaur04** [comment]
I would like to contribute to this issue. Kindly assign it to me
